tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

brew "git"
brew "mas"
brew "gh"
brew "asdf"
brew "starship"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "peco"
brew "jq" # for flutter
# brew "supabase/tap/supabase" Xcodeを15にする必要がある

cask "1password"
cask "1password-cli"
cask "xcodes"
cask "zoom"
cask "slack"
cask "docker"
cask "arc"
cask "raycast"
cask "tableplus"
cask "notion-calendar"
cask "deepl"
cask "ledger-live"
cask "postman"
cask "visual-studio-code"
cask "readdle-spark"
cask "microsoft-teams"
cask "skype"
cask "spotify"
cask "android-studio"
cask "cleanmymac"
cask "vpn-by-google-one"
cask "another-redis-desktop-manager"
cask "minisim"
cask "google-japanese-ime"
cask "karabiner-elements"
cask "google-chrome"
cask "font-fira-code-nerd-font"
cask "iterm2"
cask "discord"

mas "Magnet マグネット", id: 441258766